### ISSUE TITLE
Pausing a song does not pause the countdown.

### ISSUE THREAD

**Issue by DesperatePea** [sech1p/AppleMusic_Discord_RPC#2]
I noticed in discord, when you pause a song, the time countdown does not stop. 

macOS Monterey, 12.0.1

**Comment by d34dinsid3k1tty** [comment]
Hello! First of all, sorry for replying so late.

Thanks for reporting the *bug* (~~or maybe not the bug because I probably didn't implement it tbh~~ 👀). This will be included in the Presence [rewrite](/sech1p/AppleMusic_Discord_RPC/tree/ng) which should be coming soon.
